#!/usr/bin/env bash
# Regenerates the support table in SHADER-COMPATIBILITY.md from the corpus baseline.
#
#   scripts/shader-support-table.sh          # rewrite the generated section
#   scripts/shader-support-table.sh --check  # fail if the section is out of date
#
# The baseline is the source of truth; this file is never edited by hand.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASELINE="$ROOT/test/shader-corpus-baseline.txt"
DOC="$ROOT/SHADER-COMPATIBILITY.md"
BEGIN='<!-- BEGIN GENERATED SUPPORT TABLE -->'
END='<!-- END GENERATED SUPPORT TABLE -->'

[ -f "$BASELINE" ] || { echo "no corpus baseline at $BASELINE"; exit 1; }
[ -f "$DOC" ] || { echo "no document at $DOC"; exit 1; }

names() { awk -v v="$1" '$1 == v { print $2 }' "$BASELINE" | LC_ALL=C sort; }
count() { names "$1" | wc -l; }

section=$(
  printf '%s\n\n' "$BEGIN"
  printf 'Generated by `scripts/shader-support-table.sh` from `test/shader-corpus-baseline.txt`.\n'
  printf 'Do not edit by hand.\n\n'
  printf '| state | count | what it means |\n'
  printf '| --- | --- | --- |\n'
  printf '| Supported | %s | Compiles, and every module it emits passes `spirv-val`. |\n' "$(count PASS)"
  printf '| Supported, untested | %s | Same, but the compiler raised a warning worth checking in a game. |\n' "$(count WARN)"
  printf '| Unsupported | %s | Does not compile, for the reasons listed below. |\n' "$(count FAIL)"
  printf '\nCompiling to valid SPIR-V is verified for every shader here by the corpus.\n'
  printf 'Rendering correctly is not: that needs the shader run against a real game,\n'
  printf 'and a shader reading depth needs the depth buffer wired to show anything.\n'
  printf '\n### Supported, untested (%s)\n\n' "$(count WARN)"
  names WARN | paste -sd', ' -
  printf '\n### Unsupported (%s)\n\n' "$(count FAIL)"
  while read -r n; do
    case "$n" in
      BX_XIV_ChromakeyPlus)
        printf -- '- `%s` needs the REST addon in Final Fantasy XIV under DirectX 11. A Vulkan layer cannot provide it.\n' "$n" ;;
      BaBa_SSR)
        printf -- '- `%s` calls `tex2Dgather`, which ReShade 6.7.3 does not define, so it does not compile there either.\n' "$n" ;;
      SuperDepth3D_WoWvx)
        printf -- '- `%s` branches on a vector. ReShade rejects that with X3019; only DXC accepts it, by taking the first component.\n' "$n" ;;
      *)
        printf -- '- `%s`\n' "$n" ;;
    esac
  done < <(names FAIL)
  printf '\n### Supported (%s)\n\n' "$(count PASS)"
  names PASS | paste -sd', ' -
  printf '\n%s\n' "$END"
)

if ! grep -qF "$BEGIN" "$DOC"; then
  printf '\n%s\n' "$section" >> "$DOC"
  echo "support table appended to $DOC"
  exit 0
fi

rewritten=$(awk -v begin="$BEGIN" -v end="$END" -v repl="$section" '
  $0 == begin { print repl; skip = 1; next }
  $0 == end   { skip = 0; next }
  !skip       { print }
' "$DOC")

if [ "${1:-}" = "--check" ]; then
  if [ "$rewritten" = "$(cat "$DOC")" ]; then
    echo "support table is current"
    exit 0
  fi
  echo "SHADER-COMPATIBILITY.md is out of date -- run scripts/shader-support-table.sh"
  exit 1
fi

printf '%s\n' "$rewritten" > "$DOC"
echo "support table regenerated in $DOC"
